[default]
extend-ignore-identifiers-re = [
    # Technical terms and proper nouns
    "Shrutik",
    "শ্রুতিক",
    "Bangla",
    "PostgreSQL",
    "Redis",
    "FastAPI",
    "NextJS",
    "mdBook",
    "Alembic",
    "Celery",
    "SQLAlchemy",
    "Uvicorn",
    "Pydantic",
    "JWT",
    "CORS",
    "API",
    "REST",
    "HTTP",
    "HTTPS",
    "JSON",
    "YAML",
    "TOML",
    "CSS",
    "JS",
    "HTML",
    "URL",
    "URI",
    "UUID",
    "OAuth",
    "WebM",
    "FLAC",
    "WAV",
    "MP3",
    "M4A",
    "OGG",
    "AAC",
    # Configuration and environment
    "env",
    "localhost",
    "postgres",
    "redis",
    "nginx",
    "apache",
    "ubuntu",
    "debian",
    "centos",
    "rhel",
    "macos",
    "dockerfile",
    "kubernetes",
    "kubectl",
    "helm",
    "terraform",
    # Commands and tools
    "mkdir",
    "chmod",
    "chown",
    "sudo",
    "systemctl",
    "psql",
    "createdb",
    "dropdb",
    "alembic",
    "uvicorn",
    "celery",
    "pytest",
    "npm",
    "yarn",
    "pip",
    "venv",
    "virtualenv",
    "conda",
    # File extensions and formats
    "py",
    "js",
    "ts",
    "tsx",
    "jsx",
    "md",
    "yml",
    "yaml",
    "json",
    "toml",
    "ini",
    "cfg",
    "conf",
    "log",
    "txt",
    "csv",
    "sql",
    # GitHub and Git
    "github",
    "gitlab",
    "bitbucket",
    "git",
    "repo",
    "repos",
    "pr",
    "prs",
    "ci",
    "cd",
    "cicd"
]

[default.extend-words]
# Custom dictionary for project-specific terms
Shrutik = "Shrutik"
mdbook = "mdBook"
fastapi = "FastAPI"
nextjs = "Next.js"
postgresql = "PostgreSQL"
redis = "Redis"
alembic = "Alembic"
celery = "Celery"
sqlalchemy = "SQLAlchemy"
uvicorn = "Uvicorn"
pydantic = "Pydantic"

[files]
extend-exclude = [
    "*.log",
    "*.lock",
    "node_modules/",
    "venv/",
    ".venv/",
    "__pycache__/",
    ".git/",
    "book/",
    "target/",
    "dist/",
    "build/"
]