CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "role" varchar,
  "created_at" timestamp
);

CREATE TABLE "scripts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "text" text,
  "duration_category" varchar,
  "created_at" timestamp
);

CREATE TABLE "voice_recordings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "script_id" int,
  "file_path" varchar,
  "duration" int,
  "created_at" timestamp
);

CREATE TABLE "audio_chunks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recording_id" int,
  "chunk_index" int,
  "file_path" varchar,
  "start_time" float,
  "end_time" float,
  "created_at" timestamp
);

CREATE TABLE "transcriptions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chunk_id" int,
  "user_id" int,
  "text" text,
  "created_at" timestamp
);

CREATE TABLE "quality_reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transcription_id" int,
  "reviewer_id" int,
  "rating" int,
  "comment" text,
  "created_at" timestamp
);

ALTER TABLE "voice_recordings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "voice_recordings" ADD FOREIGN KEY ("script_id") REFERENCES "scripts" ("id");

ALTER TABLE "audio_chunks" ADD FOREIGN KEY ("recording_id") REFERENCES "voice_recordings" ("id");

ALTER TABLE "transcriptions" ADD FOREIGN KEY ("chunk_id") REFERENCES "audio_chunks" ("id");

ALTER TABLE "transcriptions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "quality_reviews" ADD FOREIGN KEY ("transcription_id") REFERENCES "transcriptions" ("id");

ALTER TABLE "quality_reviews" ADD FOREIGN KEY ("reviewer_id") REFERENCES "users" ("id");
