"""
Content library for generating unique, human-like motivational scripts.
Each piece is hand-crafted to sound natural and flow well.
"""

# Opening hooks - grab attention immediately (50 items)
OPENINGS = [
    "Let's talk about something most people get wrong.",
    "Here's what nobody tells you about getting better at anything.",
    "I used to think success was about one thing. I was completely wrong.",
    "There's a pattern I keep seeing in people who actually make progress.",
    "Most advice about improvement misses the point entirely.",
    "You know what's interesting about people who actually change?",
    "I've been thinking about why some people move forward while others stay stuck.",
    "There's a difference between knowing what to do and actually doing it.",
    "Let me share something that took me years to understand.",
    "Here's the thing about growth that surprised me most.",
    "Everyone wants results, but few people want the process.",
    "The gap between intention and action is where most dreams die.",
    "I've noticed something about people who actually finish what they start.",
    "There's a secret hiding in plain sight about skill development.",
    "Most people overcomplicate this. It's actually simpler than you think.",
    "You've probably heard this advice before, but you're hearing it wrong.",
    "The hardest part isn't what you think it is.",
    "I'm going to tell you something that might sound obvious, but stick with me.",
    "There's a reason why some people make it look easy.",
    "Let me challenge something you probably believe about improvement.",
    "Here's what changed everything for me.",
    "Most people focus on the wrong thing entirely.",
    "There's a fundamental misunderstanding about how progress actually works.",
    "I want to talk about the part nobody mentions.",
    "You know what separates people who succeed from those who don't?",
    "There's something counterintuitive about getting better at anything.",
    "Let me start with a truth that's uncomfortable but necessary.",
    "Here's what I wish someone had told me years ago.",
    "The conventional wisdom about this is backwards.",
    "There's a pattern in every success story that people miss.",
    "Most people quit right before the breakthrough. Here's why.",
    "I'm going to share the one thing that actually matters.",
    "There's a difference between busy work and real progress.",
    "Let me tell you about the moment everything clicked for me.",
    "Here's the part of the process nobody warns you about.",
    "You've been lied to about how long this takes.",
    "There's a simple truth hiding under all the complexity.",
    "Most people are optimizing for the wrong outcome.",
    "Let me explain why your current approach might be holding you back.",
    "There's something everyone who masters a skill eventually learns.",
    "Here's what the experts do that beginners don't see.",
    "I want to challenge your assumptions about what's possible.",
    "There's a critical difference between motion and progress.",
    "Let me share the hardest lesson I've learned.",
    "Here's why most people never get past the beginner stage.",
    "There's a trap that catches almost everyone. Let me show you how to avoid it.",
    "You know what's funny about expertise? It's not what you think.",
    "Let me tell you about the invisible barrier most people hit.",
    "There's one thing that predicts success better than talent or luck.",
    "Here's the uncomfortable truth about improvement.",
]

# Core insights - varied sentence structures (50 items)
INSIGHTS = [
    "Progress isn't linear. Some days you'll feel like you're moving backward. That's normal. The key is showing up anyway.",
    "The gap between where you are and where you want to be? It closes one small decision at a time.",
    "You don't need perfect conditions. You need consistent action, even when it's messy.",
    "Real skill builds slowly. Anyone promising quick results is selling something.",
    "The work that matters most often feels boring. That's actually a good sign.",
    "Your brain will resist change. It prefers familiar patterns, even bad ones.",
    "Most breakthroughs come after you've pushed through the part where you wanted to quit.",
    "The difference between amateurs and professionals? Professionals show up on bad days too.",
    "You can't think your way into a new way of acting. You have to act your way into a new way of thinking.",
    "Clarity comes from doing, not from planning to do.",
    "Momentum builds slowly, then suddenly. You won't notice it until you look back.",
    "The hardest part is starting. The second hardest part is continuing when results aren't visible yet.",
    "Your comfort zone expands every time you step outside it, even just a little.",
    "Failure isn't the opposite of success. It's part of the process of getting there.",
    "The best time to start was yesterday. The second best time is right now.",
    "You'll never feel completely ready. That feeling you're waiting for? It doesn't come before you start.",
    "Small improvements compound into remarkable results over time. Trust the process.",
    "The obstacle isn't in your way. The obstacle is the way forward.",
    "You don't rise to the level of your goals. You fall to the level of your systems.",
    "Discipline is choosing between what you want now and what you want most.",
    "The work you do when nobody's watching determines what happens when everyone is.",
    "Your current habits are perfectly designed to give you your current results.",
    "Change happens at the edge of your comfort zone, not in the middle of it.",
    "The quality of your practice matters more than the quantity of your time.",
    "You can't control outcomes, but you can control your effort and consistency.",
    "The gap between knowing and doing is where most potential dies.",
    "Your excuses are more creative than your solutions. That's the real problem.",
    "The path to mastery is paved with embarrassing early attempts. Everyone walks it.",
    "You're not behind. You're exactly where you need to be to start from here.",
    "The work compounds. The excuses don't. Choose wisely.",
    "Perfection is a trap. Progress is the goal.",
    "Your future self is counting on the decisions you make today.",
    "The difference between try and triumph is a little umph.",
    "You don't need more time. You need more focus during the time you have.",
    "The magic happens outside your comfort zone. That's why it feels uncomfortable.",
    "Your potential isn't fixed. It expands with every challenge you face.",
    "The journey of a thousand miles begins with a single step. Then another. Then another.",
    "You're building something bigger than you can see right now. Keep building.",
    "The work is the reward. The outcome is just a bonus.",
    "Your limitations are often just untested assumptions.",
    "The best investment you can make is in yourself. It always pays dividends.",
    "You don't need to see the whole staircase. Just take the first step.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Your mindset shapes your reality more than your circumstances do.",
    "The only way to do great work is to love what you do, or learn to love the process.",
    "You're not stuck. You're just committed to patterns that no longer serve you.",
    "The secret to getting ahead is getting started. The secret to getting started is breaking complex tasks into small manageable actions.",
    "Your comfort zone is a beautiful place, but nothing ever grows there.",
    "The pain of discipline weighs ounces. The pain of regret weighs tons.",
    "You are what you repeatedly do. Excellence is not an act, but a habit.",
]

# Practical examples - concrete and relatable (40 items)
EXAMPLES = [
    "Think about learning to cook. The first few meals are disasters. You burn things. You oversalt. But each mistake teaches you something specific.",
    "Consider how you learned to drive. At first, every action required conscious thought. Now you do it without thinking. That's what practice builds.",
    "Look at anyone good at their craft. They've failed more times than beginners have tried.",
    "Watch a kid learning to walk. They fall constantly. But they don't quit. They don't need motivation speeches. They just keep trying.",
    "Remember the last time you learned something new. The beginning was awkward. Then it clicked. That's the pattern every time.",
    "Take writing, for example. Your first draft is always terrible. That's not a bug, it's a feature. You can't edit a blank page.",
    "Think about athletes. They don't just practice when they feel inspired. They have a schedule and they stick to it, rain or shine.",
    "Consider musicians. They practice scales for hours. It's not glamorous, but it's what makes the performance possible.",
    "Look at successful entrepreneurs. Most of them failed multiple times before they succeeded. The difference? They kept going.",
    "Watch how children learn languages. They make mistakes constantly and don't care. They just keep talking until they get it right.",
    "Think about gardening. You plant seeds, water them, and wait. You can't rush growth. You can only create the right conditions.",
    "Consider learning a new language. The first conversations are painful. You stumble over words. But each conversation makes the next one easier.",
    "Look at how you learned to ride a bike. You fell. You got back up. You fell again. Eventually, you didn't fall anymore.",
    "Think about public speaking. The first time is terrifying. The tenth time is still scary. The hundredth time? You're comfortable.",
    "Watch how babies learn to eat. It's messy. Food goes everywhere. But they figure it out through repetition.",
    "Consider learning to code. Your first programs are full of bugs. That's how you learn what works and what doesn't.",
    "Think about learning an instrument. The first sounds you make are awful. But you keep practicing until they're not.",
    "Look at how you learned to read. First letters, then words, then sentences. Each step built on the last.",
    "Watch how people learn to swim. They start in the shallow end. They practice breathing. They build confidence gradually.",
    "Think about learning to draw. Your first sketches don't look like what you imagined. But each one teaches your hand something new.",
    "Consider how you learned to type. At first, you hunted for each key. Now your fingers know where to go automatically.",
    "Look at how chefs develop recipes. They try something, taste it, adjust it, try again. Iteration is the process.",
    "Think about learning photography. Your first hundred photos are practice. Your next hundred are learning. Then you start creating.",
    "Watch how dancers learn choreography. They break it down into small pieces, practice each piece, then put it together.",
    "Consider how you learned math. You started with counting, then addition, then multiplication. Each level built on the previous one.",
    "Think about learning to negotiate. Your first attempts are awkward. But each conversation teaches you something about timing and tone.",
    "Look at how writers develop their voice. They imitate others first, then gradually find what's uniquely theirs.",
    "Watch how comedians develop material. They test jokes, see what works, refine them, test again. It's a process of iteration.",
    "Think about learning to manage people. Your first attempts at leadership are clumsy. But you learn from each interaction.",
    "Consider how you learned to make decisions. You made bad ones, learned from them, and gradually got better at it.",
    "Look at how designers develop their eye. They study thousands of examples, try things, fail, and slowly develop taste.",
    "Think about learning to sell. Your first pitches are terrible. But each rejection teaches you something about what resonates.",
    "Watch how teachers learn to teach. Their first classes are rough. But they adapt, improve, and eventually find their rhythm.",
    "Consider how you learned to manage money. You made mistakes, learned from them, and gradually developed better habits.",
    "Think about learning to build relationships. Your first attempts at connection are awkward. But you learn what works through experience.",
    "Look at how scientists develop theories. They hypothesize, test, fail, adjust, and test again. Failure is data.",
    "Watch how craftspeople develop their skills. They make the same thing hundreds of times, each one slightly better than the last.",
    "Think about learning to lead meetings. Your first ones are disorganized. But you learn what works through trial and error.",
    "Consider how you learned to solve problems. You started with simple ones, built mental models, and gradually tackled harder ones.",
    "Look at how anyone masters anything. They start bad, stay consistent, and gradually become good. There's no shortcut.",
]

# Transitions - connect ideas naturally (30 items)
TRANSITIONS = [
    "Here's why that matters.",
    "Let me explain what I mean.",
    "This connects to something important.",
    "Now, here's the interesting part.",
    "But there's more to it.",
    "This is where it gets practical.",
    "Let's break that down.",
    "Here's what that looks like in practice.",
    "So what does this mean for you?",
    "Let me give you a concrete example.",
    "Here's where it gets interesting.",
    "Let me show you what I mean.",
    "This is the key insight.",
    "Now, pay attention to this part.",
    "Here's the thing though.",
    "Let me put it another way.",
    "This is where most people miss it.",
    "Here's the practical application.",
    "Let me connect the dots.",
    "This brings us to the core point.",
    "Here's what that actually means.",
    "Let me make this concrete.",
    "This is where theory meets reality.",
    "Here's how this plays out.",
    "Let me illustrate this.",
    "This is the crucial part.",
    "Here's what you need to understand.",
    "Let me clarify what I'm saying.",
    "This is where it all comes together.",
    "Here's the bottom line.",
]

# Challenges - acknowledge difficulties (30 items)
CHALLENGES = [
    "The hard part? Doing this when you don't feel like it. Which is most days.",
    "Nobody talks about how boring the middle part is. That's where most people quit.",
    "You'll have days where nothing seems to work. Those days matter most.",
    "The resistance never goes away. You just get better at working through it.",
    "Some days you'll question if it's worth it. That's when you need to remember why you started.",
    "The plateau phase is brutal. You're working hard but not seeing results. That's when most people give up.",
    "Your motivation will fade. That's guaranteed. The question is whether your discipline will carry you through.",
    "There will be setbacks. Plans will fall apart. Progress will stall. That's not failure, that's the process.",
    "The voice in your head will tell you to quit. It will sound very reasonable. Don't listen to it.",
    "You'll compare yourself to others and feel behind. That comparison is stealing your energy.",
    "The work will feel pointless sometimes. Like you're pushing a boulder uphill. Keep pushing anyway.",
    "You'll have to say no to things you want to do. That's the cost of saying yes to what matters most.",
    "The early results will be disappointing. Your expectations and reality won't match. Adjust your expectations, not your effort.",
    "You'll feel like an impostor. Like you don't belong. Everyone feels this way. Do it anyway.",
    "The feedback will be harsh sometimes. It will sting. Use it as fuel, not as an excuse to quit.",
    "You'll want to skip days. You'll have good reasons. Do it anyway, even if it's just for five minutes.",
    "The progress will be invisible for a long time. You'll wonder if anything is changing. It is.",
    "You'll hit walls that seem impossible to break through. They're not. They just require a different approach.",
    "The people around you might not understand. They might discourage you. Their doubt doesn't define your potential.",
    "You'll have to start over sometimes. All that progress, gone. But you'll rebuild faster the second time.",
    "The work will interfere with your comfort. With your routine. With your leisure time. That's the price.",
    "You'll make mistakes that feel catastrophic. They're not. They're just expensive lessons.",
    "The uncertainty will be uncomfortable. You won't know if it's working until much later. Trust the process anyway.",
    "You'll feel overwhelmed by how much there is to learn. Break it down. One piece at a time.",
    "The sacrifices will feel heavy sometimes. You'll wonder if it's worth it. Future you will answer that question.",
    "You'll have to do things badly before you can do them well. That's humbling. Do them badly anyway.",
    "The criticism will come from people who've never tried what you're attempting. Consider the source.",
    "You'll want results faster than they come. Impatience is natural. Patience is necessary.",
    "The work will expose your weaknesses. That's uncomfortable. It's also how you grow.",
    "You'll have to keep going when you can't see the finish line. That's the hardest part. It's also what separates those who make it from those who don't.",
]

# Encouragement - realistic but supportive (30 items)
ENCOURAGEMENT = [
    "But here's the good news: you don't need to be perfect. You just need to be consistent.",
    "The beautiful thing? Small actions compound over time in ways you can't predict.",
    "You're already further along than you think. Every attempt counts.",
    "Progress happens in the background while you're focused on the work.",
    "The fact that you're still here, still trying? That already puts you ahead.",
    "You have more strength than you realize. You've overcome challenges before. You'll overcome this one too.",
    "The path gets clearer as you walk it. You don't need to see the whole journey, just the next step.",
    "Every expert was once a beginner who didn't quit. You're on the same path they walked.",
    "Your effort is never wasted. Even when results aren't visible, you're building something.",
    "The work you're doing today is creating opportunities you can't see yet. Keep going.",
    "You're not starting from zero. You're starting from experience. That counts for something.",
    "The fact that it's hard means you're growing. Easy doesn't build strength.",
    "You've already proven you can start. Now prove you can continue. That's where the real growth happens.",
    "Your consistency is more impressive than you think. Most people don't make it this far.",
    "The skills you're building will serve you in ways you can't imagine yet. Trust the investment.",
    "You're allowed to be a work in progress. That's what growth looks like.",
    "The doubt you feel is normal. It doesn't mean you're on the wrong path. It means you're on a challenging one.",
    "You're building momentum even when you can't feel it. Physics works whether you believe in it or not.",
    "The version of you that can do this already exists. You're becoming that person right now.",
    "Your persistence is your superpower. Talent is common. Persistence is rare.",
    "You're not behind schedule. You're exactly where you need to be to learn what you need to learn.",
    "The work is shaping you into someone capable of handling what comes next. Trust the process.",
    "You've survived every difficult day so far. Your track record is perfect.",
    "The breakthrough often comes right after you want to quit. You might be closer than you think.",
    "You're doing better than you give yourself credit for. Progress is hard to see from the inside.",
    "The fact that you're trying makes you braver than most. Courage isn't the absence of fear.",
    "You're building something that will outlast your current feelings. Feelings change. Progress accumulates.",
    "Your future self is rooting for you. Don't let them down.",
    "You have everything you need to take the next step. You don't need everything to finish, just to continue.",
    "The work you're doing matters. Maybe not today, maybe not tomorrow, but it compounds into something significant.",
]

# Reflections - deeper thinking (30 items)
REFLECTIONS = [
    "Think about what you're building. Not just the end result, but who you're becoming in the process.",
    "The skills you develop along the way often matter more than the goal itself.",
    "Every time you choose to show up, you're reinforcing a new identity.",
    "The person who can do this thing you're working toward? You're becoming that person right now.",
    "Your future self will thank you for the work you're doing today, even when it feels pointless.",
    "Consider the ripple effects of your effort. You're not just changing yourself, you're changing what's possible.",
    "The journey is teaching you things the destination never could. Pay attention to the lessons.",
    "You're writing a story with your actions. What do you want that story to say?",
    "The struggle isn't a detour from the path. The struggle is the path.",
    "You're not just building a skill. You're building proof that you can do hard things.",
    "The person you're becoming is more valuable than the thing you're trying to achieve.",
    "Every choice to continue is a vote for the person you want to be.",
    "You're creating evidence for yourself. Evidence that you can commit. That you can persist. That you can grow.",
    "The work is changing you in ways you won't recognize until you look back.",
    "You're not just practicing a skill. You're practicing discipline, patience, and resilience.",
    "The goal is just a direction. The real value is in who you become while moving toward it.",
    "You're building a relationship with yourself. One where you keep the promises you make.",
    "The effort you put in today is a gift to your future self. They'll need the strength you're building.",
    "You're not just learning what to do. You're learning who you are when things get difficult.",
    "The process is revealing your character and building it at the same time.",
    "You're creating a track record of following through. That's worth more than talent.",
    "The work is a mirror. It shows you what you're capable of when you don't quit.",
    "You're not just moving toward a goal. You're moving away from who you used to be.",
    "Every rep, every practice, every attempt is a conversation with your potential.",
    "You're building trust with yourself. That's the foundation everything else is built on.",
    "The discomfort you feel is growth happening in real time. Don't run from it.",
    "You're not just developing a skill. You're developing the ability to develop skills.",
    "The work is teaching you that you're more capable than you thought. That lesson is priceless.",
    "You're creating a new normal. What feels hard today will feel routine tomorrow.",
    "The journey is transforming you into someone who doesn't need motivation to do what matters.",
]

# Closings - memorable endings (25 items)
CLOSINGS = [
    "So start small. Start messy. Just start.",
    "The work is waiting. It doesn't care about your excuses or your perfect plan.",
    "You already know what to do. Now it's just about doing it.",
    "Tomorrow you'll either wish you started today, or you'll be glad you did.",
    "The path forward is simple. Not easy, but simple. One step, then another.",
    "Stop waiting for the right moment. This is it.",
    "You don't need more information. You need more action.",
    "The difference between who you are and who you want to be? It's built one day at a time.",
    "The work won't do itself. But you can do it. So do it.",
    "Your move. Make it count.",
    "The clock is ticking. Not to pressure you, but to remind you that time passes whether you act or not.",
    "You have two choices: start now or wish you had. Choose wisely.",
    "The journey begins with a decision. Make it. Then make the next one. Then the next.",
    "You're ready. You might not feel ready, but you are. Prove it to yourself.",
    "The world needs what you're building. But more importantly, you need who you're becoming.",
    "Stop thinking. Start doing. Adjust as you go.",
    "The best project you'll ever work on is you. Get to work.",
    "You can make excuses or you can make progress. You can't make both.",
    "The finish line is built from starting lines. Cross this one.",
    "Your potential is waiting on the other side of action. Go meet it.",
    "The work is simple: show up, do the thing, repeat. Don't complicate it.",
    "You've spent enough time preparing. Now it's time to perform.",
    "The gap between where you are and where you want to be closes one action at a time. Take one.",
    "You're capable of more than you think. But you'll never know until you try.",
    "The journey of transformation starts now. Not tomorrow. Not next week. Now.",
]

# Questions - engage thinking (25 items)
QUESTIONS = [
    "What would happen if you committed to this for just 30 days?",
    "What's the smallest step you could take right now?",
    "If you knew you couldn't fail, what would you try?",
    "What's stopping you? Really stopping you, not the excuse you tell yourself?",
    "A year from now, what will you wish you had started today?",
    "What would you do if you weren't afraid of looking foolish?",
    "How would your life be different if you actually followed through this time?",
    "What's the cost of staying where you are?",
    "If not now, when? If not you, who?",
    "What would you attempt if you knew you had unlimited time to figure it out?",
    "What's more scary: trying and failing, or never trying at all?",
    "What would the person you want to become do right now?",
    "What's one thing you could do today that your future self would thank you for?",
    "What are you pretending not to know?",
    "What would you do if you trusted yourself completely?",
    "What's the real reason you haven't started yet?",
    "How much longer are you willing to wait for the perfect moment?",
    "What would change if you gave yourself permission to be bad at this at first?",
    "What's the worst that could happen if you tried? What's the best?",
    "What would you tell your best friend if they were in your situation?",
    "What are you capable of that you haven't tested yet?",
    "What would you do differently if you knew no one was watching?",
    "What's the gap between what you say you want and what your actions show you want?",
    "What would happen if you stopped waiting to feel motivated?",
    "What's one belief about yourself that might not be true?",
]

# Observations - universal truths (30 items)
OBSERVATIONS = [
    "Everyone who's good at something was once bad at it.",
    "The people you admire? They have bad days too. They just don't let that stop them.",
    "Talent is overrated. Consistency beats talent every time.",
    "You don't need to love the process. You just need to respect it.",
    "The work doesn't get easier. You get stronger.",
    "Success is boring. It's the same actions repeated until they produce results.",
    "The difference between professionals and amateurs isn't talent. It's showing up when you don't feel like it.",
    "Nobody feels confident before they start. Confidence comes from doing, not from feeling ready.",
    "The people who make it look easy have failed more times than you've tried.",
    "Motivation is fickle. Discipline is reliable. Build systems, not reliance on feelings.",
    "The best time to plant a tree was 20 years ago. The second best time is now. Same applies to everything.",
    "You can't edit a blank page. You can't improve what doesn't exist. Create first, perfect later.",
    "The obstacle is the way. What's blocking you is actually showing you where to focus.",
    "Everyone starts at zero. The only difference is some people start and others don't.",
    "The work you avoid is usually the work that matters most.",
    "Perfection is procrastination in disguise. Done is better than perfect.",
    "The gap between knowing and doing is where dreams go to die.",
    "You don't need more time. You need more focus. Everyone has the same 24 hours.",
    "The magic you're looking for is in the work you're avoiding.",
    "Comfort is the enemy of growth. If it's easy, you're not growing.",
    "The people who succeed aren't smarter. They're just more persistent.",
    "You can't think your way into action. You have to act your way into clarity.",
    "The best way to predict the future is to create it. One action at a time.",
    "Failure is feedback. The only real failure is not trying.",
    "The journey is long. That's not a bug, it's a feature. Quick results don't last.",
    "You're not competing with others. You're competing with who you were yesterday.",
    "The work compounds. Today's effort adds to yesterday's. That's how mountains are built.",
    "You can't control outcomes. You can only control effort. Focus on what you can control.",
    "The path to mastery is paved with embarrassing early attempts. Everyone walks it. No exceptions.",
    "Your current situation is the result of your past decisions. Your future situation will be the result of your current ones.",
]
